server:
  port: 8082

spring:
  application:
    name: ApiGateway-Service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  # change eureka service name

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

